name: Export and Upload to itch.io

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Godot
        uses: firebelley/godot-export@v1
        with:
          godot-version: "4.3"

      - name: Export project
        run: |
          mkdir -p export
          godot --export "HTML5" export/index.html

      - name: Upload to itch.io
        uses: leafo/itchio-action@v1
        with:
          api_key: ${{ secrets.BUTLER_API_KEY }}
          target: "user/game:html5"
          file: "export/index.html"
