name: Build Godot Project
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  export_web:
    name: Export
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Download Godot executable and templates
        run: |
          curl -L -o Godot_v4.3-stable_win64.zip https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_win64.zip
          curl -L -o Godot_v4.3-stable_export_templates.tpz https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_export_templates.tpz
      - name: Extract Godot
        run: |
          mkdir -p godot
          tar -xf Godot_v4.3-stable_win64.zip -C godot
      - name: Build and export
        id: export
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: ./godot/Godot.exe # Path to the extracted Godot executable
          godot_export_templates_download_url: ./Godot_v4.3-stable_export_templates.tpz
          relative_project_path: ./game/
          archive_output: true
          use_preset_export_path: true
          export_debug: false
      - name: Upload web build to itch
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{ secrets.BUTLER_API_KEY }}
          gameData: ./exports/web/index.zip
          itchUsername: ${{ secrets.ITCH_USER }}
          itchGameId: ld56
          buildChannel: html5
