on:
  push:
    branches:
      - main

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export game to GitHub
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0

      - name: Download Godot
        run: |
          wget https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_linux.x86_64.zip -O godot.zip
          unzip godot.zip -d ~/godot
          chmod +x ~/godot/Godot_v4.3-stable_linux.x86_64

      - name: Download Godot export templates
        run: |
          wget https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_export_templates.tpz -O 4.3.stable.tpz
          unzip 4.3.stable.tpz -d ~/.local/share/godot/export_templates
          mv ~/.local/share/godot/export_templates/templates ~/.local/share/godot/export_templates/4.3.stable
      - name: Export game
        run: |
          ~/godot/Godot_v4.3-stable_linux.x86_64 --headless --export-release "Web" ./build/html/LD56.html
        env:
          GITHUB_TOKEN: ${{ secrets.GH_KEY }}

      - name: Upload to itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: html
          ITCH_GAME: ld56
          ITCH_USER: thomas-bringer
          PACKAGE: ./build/html
