name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Build:
    runs-on: windows-latest
    env:
      BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
      ITCHIO_USERNAME: ${{ secrets.ITCHIO_USERNAME }}
      PROJECT_NAME: "ld56"
      GODOT_VERSION: "4.3" # Manually set Godot version

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Debug URL
        run: |
          echo "Downloading Godot from: https://downloads.tuxfamily.org/godotengine/${{GODOT_VERSION}}/Godot_v${{GODOT_VERSION}}-stable_win64.zip"

      - name: Download Godot
        run: |
          curl -v -L -o godot.zip https://downloads.tuxfamily.org/godotengine/${{GODOT_VERSION}}/Godot_v${{GODOT_VERSION}}-stable_win64.zip
          if ((Get-Item "godot.zip").Length -lt 1000) {
            Write-Error "Godot download failed or file is too small."
            exit 1
          }
          powershell -Command "Expand-Archive -Path 'godot.zip' -DestinationPath 'godot'"

      - name: Download Export Templates
        run: |
          curl -v -L -o export_templates.zip https://downloads.tuxfamily.org/godotengine/${{GODOT_VERSION}}/Godot_v${{GODOT_VERSION}}-stable_export_templates.tpz
          if ((Get-Item "export_templates.zip").Length -lt 1000) {
            Write-Error "Export templates download failed or file is too small."
            exit 1
          }
          powershell -Command "Expand-Archive -Path 'export_templates.zip' -DestinationPath 'export_templates'"

      - name: Setup Export Templates
        run: |
          mkdir -p $env:LOCALAPPDATA\share\godot\export_templates\${{GODOT_VERSION}}.stable
          Copy-Item -Path export_templates\* -Destination $env:LOCALAPPDATA\share\godot\export_templates\${{GODOT_VERSION}}.stable

      - name: Run Godot Export
        run: |
          .\godot\Godot.exe --headless --export-release html

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: html/
