name: Export and Upload to itch.io

on:
  push:
    branches:
      - main

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export game to Github
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download Godot
        run: |
          wget https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_linux.x86_64.zip -O godot.zip
          unzip godot.zip -d ~/godot
          chmod +x ~/godot/Godot_v4.3-stable_linux.x86_64

      - name: Download Godot export templates
        run: |
          wget https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_export_templates.tpz -O export_templates.tpz
          mkdir -p ~/.local/share/godot/templates/4.3.stable
          unzip export_templates.tpz -d ~/.local/share/godot/templates/4.3.stable

      - name: Set permissions
        run: |
          chmod -R 777 ~/.local/share/godot/templates/4.3.stable

      - name: Export game
        run: |
          mkdir -p build/html
          ~/godot/Godot_v4.3-stable_linux.x86_64 --headless --export-release "Web" build/html/LD56.html
        env:
          GITHUB_TOKEN: ${{ secrets.GH_KEY }}

      - name: Upload to itch.io
        uses: game-ci/itchio-push@v1
        with:
          api_key: ${{ secrets.ITCHIO_API_KEY }}
          target: "user/game:html5"
          file: "build/html/LD56.html"
